### ISSUE TITLE
Ability to change cursor

### ISSUE THREAD

**Issue by nathanjohnson320** [PolymerElements/paper-item#17]
It would be nice to be able to apply a custom CSS variable to the paper-items so when hovering it would be a hand as opposed to a text selector.

**Comment by notwaldorf** [comment]
You can style the cursor using the `--paper-item` mixin. In your demo, you can add something like this in a `<style is="custom-style">` tag:

```css
paper-item {
  --paper-item: {
    cursor: pointer;
    /* any other styles here */
  };
}
```
